# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Copy Docket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Copy Docket

  target 'Copy DocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Copy DocketUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
#pod 'FBSDKLoginKit'
#pod 'FacebookCore'
#pod 'FacebookLogin'
#pod 'FacebookShare'
#pod 'GoogleSignIn'
pod 'CodableFirebase'
pod 'JGProgressHUD'
pod 'BraintreeDropIn'
pod  'Kingfisher'
pod 'Alamofire'
pod 'Stripe'
pod 'IQKeyboardManagerSwift'
end
